### PR TITLE
Added DocumentDB information

### PR DESCRIPTION
**Pull request by tstringer**
Create simple how-to and a little sample Node.js code interacting with DocumentDB.

### CODE REVIEW

**Comment by romuloctba** [comment]
sweet :clap:

**Comment by tstringer** [comment]
@romuloctba, thanks! :+1: 

Hey, @mousetraps, is there anything else you want to see in this PR?

**Comment by tstringer** [comment]
Fixed PR so that there are no merge conflicts at the moment :white_check_mark:

**Comment by mousetraps** [comment]
:+1:

**Pull request merged**
