### PR TITLE
Visual C++ Build Tools link fixed

### LINKED ISSUE #50: Link to Visual C++ Build Tools in windows-environment.md is broken
As issue title describes

### PR DESCRIPTION
**Pull request by christopheranderson**
Technical Preview has closed. It's now GAd..

close #50

### CODE REVIEW

**Comment by christopheranderson** [comment]
I'll merge this myself in a day if no one has any feedback. ⏳

**Comment by orangemocha** [comment]
With the latest release of the tools, the Default Install option is all that's needed. See https://github.com/nodejs/node-gyp/commit/088082766caf7562540d0cf1ef7960a7f11995c9#diff-04c6e90faac2675aa89e2176d2eec7d8R46

**Comment by christopheranderson** [comment]
Updated message to match what node-gyp recommends.

**Comment by orangemocha** [comment]
LGTM

**Pull request merged**
