### PR TITLE
Adds notes on accessing platform APIs

### PR DESCRIPTION
**Pull request by SteveALee**

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Sorry about that, but you'll have to rebase now and move this (good!) addition into the new file. Again, sorry about that :)

**Comment by mousetraps** [comment]
It would also be good to link to section we have in windows-development.md on compiling native addons in windows.

**Comment by felixrieseberg** [comment]
Oh, good point. Coming right up.

**Comment by SteveALee** [comment]
OK, will have to wait till at PC as I did PR the lazy way via editing in the web app.

Good point re section on compiling native addons

**Comment by SteveALee** [comment]
I'll do #14 also.

**Comment by SteveALee** [comment]
PK rebase done (in a suboptimal! way)

**Comment by mousetraps** [comment]
LGTM, though what do you think about moving this to to application-tips.md instead?

**Comment by SteveALee** [comment]
@mousetraps OK.

1) I did feel it did not quite fit in that section given it's new name and current contents.
2) I suppose this is really about windows specific APIs and that's going to be in Apps not modules

**Comment by SteveALee** [comment]
@mousetraps OK I moved the notes

**Comment by mousetraps** [comment]
:+1:

**Pull request merged**
